### ISSUE TITLE
Dialog (Modal) Pattern

### ISSUE THREAD

**Issue by parrys18** [w3c/aria-practices#2799] opened 2023-09-07 10:57 UTC
I notice in bed ARIA APG Dialog (Modal) Pattern it suggests making the first interactive element in a dialog the thing that takes focus when it is opened, or, otherwise putting a tabindex of -1 on something at the top of the dialog. Why would you not put the tabindex of -1 on the element with the role of dialog itself? That way, you start right at the top of the dialog and the role dialog and the label of the dialog are read with a screen reader? This seems to work better with screen reading software to my mind?

**Comment by mcking65** [comment] 2023-10-23 20:46
The dialog is a container that contains many elements. If a dialog were focused, what would a screen reader read if the user presses a command to read the current focus?

**Comment by accdc** [comment] 2023-10-23 21:11
It only reads the accessible name if focused to.

Personally I am not in favor of allowing the dialog container to receive focus as a practice, because historically it presents discoverability issues for screen reader issues. If focus is not moved into a dialog it cannot be confined within it as expected to ensure accessibility.

**Comment by parrys18** [comment] 2023-10-23 23:14
Then what is the point of giving it an accessible name? It works great in my opinion: it makes sense to start right at the very top of the dialog so that users are orientated logically, the role (dialog) and name of the dialog are then read immediately, and users then know how to proceed to read the contents from there. Just my thoughts though.

Thanks

Sarah
________________________________

**Comment by accdc** [comment] 2023-10-25 15:44
If it can be made to work consistently across devices and platforms then I am open to it, but historically it hasn't.

Dialog also doesn't work like a named region, so the beginning and ending boundaries are never conveyed, so if a screen reader fails to confine reading focus within the dialog then a user arrowing down the page will not know where the dialog begins and ends.

The way the mappings work, the role of dialog maps to it's equivalent on the platform accessibility API, so the accessible name of a dialog acts in the same manner as a title does on a native dialog. As such, when focus is moved into the dialog, to a button within the dialog for instance, it will automatically announce the dialog title. The ARIA role of dialog does the same thing, where the accessible name of the dialog will automatically be announced when focus is moved to an element within the dialog container.

**Comment by mcking65** [comment] 2023-10-31 03:14
@parrys18 wrote:

> Then what is the point of giving it an accessible name?

The accessible name of a dialog is the "title" of the dialog window. This is typically announced when:
* The dialog is opened
* The user presses the window title command, e.g., Jaws>insert+t, NVDA>insert+t, VO:Ctrl+Opt+F2

This is also how native Windows, macOS, and Linux  dialogs work.

>It works great in my opinion: it makes sense to start right at the very top of the dialog so that users are orientated logically, the role (dialog) and name of the dialog are then read immediately, and users then know how to proceed to read the contents from there. Just my thoughts though. Thanks Sarah

It might seem to work for a subset of screen reader commands, but focusing the dialog container, because it is a window, inherrently creates inconsistencies between different screen reader commands. Specifically, the focus is on something that cannot and should not be perceivable by a reading cursor, and this has unavoidable negative side effects.

To understand the inconsistencies and consequent side effects, it is necessary to understand the difference between a dialog boundary and other kinds of boundaries from the perspective of a screen reader.

Unlike other types of containers, e.g., a list, radio group, or table, a dialog is a "window" container. The purpose of a window boundary is to constrain the screen reader's reading cursor. The idea is to make sure that the content inside the window is completely separated from the content outside the window. A window boundary is like an invisible wall. You only perceive it by bumping into it.

On the other hand, the boundary of a table or list is more like a line that you can easily walk across. Screen readers tell you about the line. You can perceive it with a reading cursor, e.g., the JAWS virtual cursor or the VoiceOver cursor.

One expected behavior that is consistent across screen readers is that if you can focus an element, you can read the element. That is, you can always move your reading cursor to the element that is focused. This is something that people do frequently in order to get more information about the focused element. For example, with the reading cursor, users can move through the characters of the element's name or even select and copy it.

So, for example, VoiceOver has a command to move the VoiceOver cursor to the focused element and JAWS has a command to move the JAWS virtual cursor to the focused element. There are also commands for reading the element that is at the location of the reading cursor and the element that is focused.

These basic functions can't work if an invisible window boundary is focused. How that impacts each screen reader experience varies. While none of the side effects create blocking conditions that make an experience inaccessible, they can certainly degrade the experience.

I wouldn't go so far as to claim that it would be impossible to devise a new set of standard screen reader behaviors for dialogs that receive focus. While in discussions about the HTML dialog element, I gave this a lot of thought. In the end, it always felt like it should be an error condition because there would have to be some screen reader commands that would simply have to gracefully fail. So, in HTML, it is a last resort fallback.

So, while it is true that reading cursors generally land at the top, that is not the only important behavior. The only way to avoid negative side effects across platforms and screen readers is to focus an element inside the dialog.

I hope this answers your question. I am closing the issue. Please feel free to re-open if that is not the case.

**Closed by mcking65** 2023-10-31 03:14 UTC
