### ISSUE TITLE
Accordion example - javascript errors in IE11, Edge and Chrome (PC)

### ISSUE THREAD

**Issue by arbydev** [w3c/aria-practices#444] opened 2017-08-21 17:11 UTC
Hi, I tried using your accordion example:
http://www.w3.org/TR/wai-aria-practices-1.1/examples/accordion/accordion.html

I found issues with the example on a PC in the following browsers:

In Internet Explorer 11.540.15063.0
Selecting the expand/collapse panels results in no expand/collapsing using either your keyboard or mouse.

In Microsoft Edge 40.15063.0.0
The "Personal Information" does expand/collapse when selected but selecting "Billing Address" or "Shipping Address" results in a slight visual change but the actual panel contents are not visible.

In Chrome (on PC) Version 60.0.3112.101 (Official Build) (64-bit)
Using a mouse click the heading does expand/collapse the panel however if you click directly on the caret symbol on the right it does not expand/collapse the panel. In Firefox clicking the caret properly performs the action.

**Comment by nschonni** [comment] 2017-08-21 19:34
Duplicate of #424

**Closed** 2017-08-22 11:44 UTC
