### ISSUE TITLE
Modal Dialog Example: Background not entirely inert; it allows selection.

### ISSUE THREAD

**Issue by erikkroes** [w3c/aria-practices#552] opened 2017-11-29 09:13 UTC
In the [modal dialog example](https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html), the background is not entirely inert.

In Safari and Chrome (macOS) I can make a selection with my mouse that starts in the dialogs, but by dragging further, I can include the content in the background. I believe this can be fixed in CSS with user-select: none (and variants) on the `base_window_layer` container.

In Chrome using VoiceOver I can reach items in the background (headings, links, etc) by using the rotor and navigating the page item by item. I believe this can be fixed with `aria-hidden="true"` on the `base_window_layer` container.

**Comment by mcking65** [comment] 2017-11-29 11:23
erikkroes commented:

> In the [modal dialog example](https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html), the background is not entirely inert.
>
> In Safari and Chrome (macOS) I can make a selection with my mouse that starts in the dialogs, but by dragging further, I can include the content in the background. I believe this can be fixed in CSS with user-select: none (and variants) on the `base_window_layer` container.

Hmm, interesting catch. Selecting isn't really operating, but it does seem reasonable to disable it.

> In Chrome using VoiceOver I can reach items in the background (headings, links, etc) by using the rotor and navigating the page item by item. I believe this can be fixed with `aria-hidden="true"` on the `base_window_layer` container.

Disabling screen reader operability of background content is part of supporting `aria-modal="true"`, which is the responsibility of the assistive technology. 
As described in the [Read Me First](http://w3c.github.io/aria-practices/#read_me_first) section, the examples in this guide intentionally do not implement techniques to cover up for lack of support for an ARIA feature.

I will change the title of this issue to capture the selection problem.

@sh0ji is already fixing issue #523. Evan, could you include this issue with selection?

**Comment by erikkroes** [comment] 2017-11-29 11:32
When I read the specs on `aria-modal="true"` I see the following:
>  Assistive technologies MAY limit navigation to the modal element's contents.

Is it then reasonable to depend on `aria-modal="true"`?

**Comment by mcking65** [comment] 2017-11-29 11:55
@erikkroes commented:

> When I read the specs on aria-modal="true" I see the following:
>
> > Assistive technologies MAY limit navigation to the modal element's contents.
>
> Is it then reasonable to depend on aria-modal="true"?

Yes, that is precisely the intent of the spec.

**Comment by erikkroes** [comment] 2017-11-29 12:11
Hmm, interesting. Because the behaviour differs between Chrome and Safari, both with Voiceover. So it looks like the choice to limit is not being made within AT, but rather within the browser. I guess support isn't there yet. Thanks for the feedback.

(and I just actually read the page properly. Totally missed `aria-hidden` being mentioned.)

**Comment by mcking65** [comment] 2018-02-13 08:17
@erikkroes, with some reluctance, the task force believes it is better to close this without fixing. While the issue is valid, it is an edge case where a robust solution adds significant complexity. In an attempt to keep the APG examples as focused as possible on the ARIA implementation and less on other aspects of web engineering, this seems like a reasonable trade off to the group.

If after reviewing pull #583 and @sh0ji's comments in it, you believe this is not the best course, feel free to re-open this issue and explain why.

**Closed by mcking65** 2018-02-13 08:17 UTC
Labels: Feedback, bug, code example
