### ISSUE TITLE
Request - Old aria practices URLs point to 404 Not Found

### ISSUE THREAD

**Issue by giacomo-petri** [w3c/aria-practices#2362] opened 2022-05-27 16:07 UTC
- Description: Old aria-practices URLs are pointing to 404 Not Found page.
- Request: Would be possible to redirect users to the new pages?
- Example: 
   - old URL: https://www.w3.org/TR/wai-aria-practices-1.2/examples/combobox/combobox-datepicker.html
   - new URL: https://www.w3.org/WAI/ARIA/apg/example-index/combobox/combobox-datepicker.html

Thanks,
Giacomo

**Comment by anuraghazra** [comment] 2022-06-01 17:36
+1 

Also would be nice if we provide anchor links in the headers, There's no longer `#` in headers which I can click and get the link of the section. 

For example in this page 
https://www.w3.org/WAI/ARIA/apg/practices/keyboard-interface
There is no way to link to the roving tabindex pattern directly. 

> Fun fact: although attaching the old hash does work `/#kbd_roving_tabindex`

**Comment by mcking65** [comment] 2022-07-24 03:10
This issue is duplicate of #2335, which is resolved.

The permalink request from @anuraghazra  will be addressed by w3c/wai-aria-practices#152.

**Closed by mcking65** 2022-07-24 03:10 UTC
