### ISSUE TITLE
Create APG Example Coding Style Guide

### ISSUE THREAD

**Issue by jnurthen** [w3c/aria-practices#66] opened 2016-07-18 18:26 UTC
Current Status

https://ianpouncey.github.io/code-guide/

**Comment by jnurthen** [comment] 2016-07-18 18:27
@ianpouncey

**Comment by jnurthen** [comment] 2016-07-18 18:29
@ianpouncey Add a coding style to not use background images for meaningful content - either use ::before and content or real <IMG> elements

**Comment by mcking65** [comment] 2016-08-13 19:09
Duplicate of #12

**Closed by mcking65** 2016-08-13 19:09 UTC
Labels: duplicate
