### ISSUE TITLE
Accordion example: MacOS VoiceOver next item focuses incorrect element

### ISSUE THREAD

**Issue by DavidMacDonald** [w3c/aria-practices#247] opened 2017-01-19 18:45 UTC
In VoiceOver, when I get to the last accordion heading.  hit enter to open. I would expect the next thing when I move to next element (Opt+CTL+right arrow) would be the content of that tab. It visually shows but VoiceOver goes to the entire Accordion container. I think what is happening is the content expands above the VO focus

**Comment by sh0ji** [comment] 2018-05-21 18:59
@DavidMacDonald, are you still seeing this issue? I'm not able to replicate it on either [the current editor's draft](http://w3c.github.io/aria-practices/examples/accordion/accordion.html) or [the current TR](https://www.w3.org/TR/wai-aria-practices-1.1/examples/accordion/accordion.html).

The steps I took were: 
1. navigate to the last accordion heading ("Shipping Address")*
1. click the button
1. use the VO command to navigate to the next element (<kbd>ctrl + opt + right arrow</kbd>)
This first label element is read ("Address 1"), which is what I expect to occur.

\* I tried getting there a few different ways:
* via headings (<kbd>VO + h</kbd>)
* via the accordion arrow navigation (up/down arrows)
* via VO arrowing (<kbd>ctrl + opt + right arrow</kbd>)

**Comment by mcking65** [comment] 2018-06-12 00:58
@DavidMacDonald, I am closing this as invalid because we can't repro. Please feel free to re-open if you have details that could help us reproduce the problem.

**Closed by mcking65** 2018-06-12 00:58 UTC
Labels: Feedback, bug, invalid
