### ISSUE TITLE
Accordion Example: Clicking chevron icon does not expand/collapse accordion

### ISSUE THREAD

**Issue by Scott-MacD** [w3c/aria-practices#547] opened 2017-11-28 03:04 UTC
Due to the way the events are bound to the accordion, when clicking the `.Accordion-icon` chevron icon, the click event does not trigger the event listener callback on the button. Arguably this is a purely presentational element and the extra markup is unnecessary. I propose removing the `.Accordion-icon` element and instead implementing this visual identifier using the `:after` pseudo element. This would fix the event listener issue, as the pseudo element is considered part of the button and at the same time would allow the removal of an extra non-semantic element from the html.

I am happy to contribute a pull request to make this revision if everyone agrees with the issue/solution.

**Comment by gerardkcohen** [comment] 2017-11-28 08:26
@Scott-MacD `pointer-events: none;` is used on the icon so any clicks should passing through to the container. Can you provide any browser/ OS info? Currently unable to reproduce. Thanks!

**Comment by Scott-MacD** [comment] 2017-11-28 14:21
Hi @gerardkcohen, it looks like the example on the actual documentation page does not include the latest code from the repo, which includes `pointer-events: none;` on both `.Accordion-icon` and `.Accordion-title`; I would still argue that `.Accordion-icon` is purely presentational and provides no additional value being a separate element, however updating the documentation so it includes the latest repo code would fix this issue.

https://www.w3.org/TR/wai-aria-practices/examples/accordion/accordion.html

Failing with Chrome 62, on Windows and Mac, and Edge 40. Works with the latest Firefox Developer Edition.

**Comment by mcking65** [comment] 2017-11-29 06:29
@Scott-MacD, we will be publishing again in December, most likely on December 12. That will be our first official release of this document; not a working draft. Thanks for the feedback.

**Comment by mcking65** [comment] 2017-11-29 08:47
@Scott-MacD, closing as resolved. Feel free to re-open if you do not agree.

**Closed by mcking65** 2017-11-29 08:47 UTC
Labels: code example, Feedback
