### ISSUE TITLE
Focus / Hover colour for accordion headers wrong

### ISSUE THREAD

**Issue by jnurthen** [w3c/aria-practices#2333] opened 2022-05-19 16:40 UTC
Go to https://www.w3.org/WAI/ARIA/apg/example-index/accordion/accordion.html
tab or hover or hover over the accordion headers

Note the colour is white on light blue

**Comment by jnurthen** [comment] 2022-05-19 16:41
This does NOT reproduce on https://w3c.github.io/aria-practices/examples/accordion/accordion.html

**Comment by jnurthen** [comment] 2022-05-19 16:43
CSS on the web version is
.button:focus, .button:hover, .stealthy-link:focus span.button, .stealthy-link:hover span.button, button:focus, button:hover {
    background-color: #036;
    background-color: var(--w3c-blue);
    color: #fff;
    color: var(--pure-white);
}

on the "document" version this CSS is not there.

**Comment by mcking65** [comment] 2022-06-12 18:36
duplicate of w3c/wai-aria-practices#105

We will address this in the site template.

**Closed by mcking65** 2022-06-12 18:36 UTC
