### ISSUE TITLE
Navigation Menubar Example: When focus is in 2nd level submenu, Escape is closing both submenus instead of focusing on parent in first level submenu.

### ISSUE THREAD

**Issue by katiehockman** [w3c/aria-practices#595] opened 2018-02-05 21:56 UTC
https://www.w3.org/TR/wai-aria-practices/#menu
"Escape: Close the menu that contains focus and return focus to the element or context, e.g., menu button or parent menuitem, from which the menu was opened."

Technically, if in a submenu then the element that opened that submenu would be the menuitem one level up. The example in the APG shows that Escape closes the entire menu, instead of just the current submenu though. Could this be made clearer in the APG of what to do in the case of currently being in a submenu?

**Comment by 0ddfell0w** [comment] 2018-02-05 22:07
Potentially a duplicate of #451

**Comment by mcking65** [comment] 2018-02-05 22:08
katiehockman commented:

> https://www.w3.org/TR/wai-aria-practices/#menu
> "Escape: Close the menu that contains focus and return focus to the element or context, e.g., menu button or parent menuitem, from which the menu was opened."
>
> Technically, if in a submenu then the element that opened that submenu would be the menuitem one level up. The example in the APG shows that Escape closes the entire menu, instead of just the current submenu though. Could this be made clearer in the APG of what to do in the case of currently being in a submenu?

That sounds like a bug in the example. Which example is closing more than one level of menu?

**Comment by 0ddfell0w** [comment] 2018-02-05 22:13
If you open the [first menubar example](https://www.w3.org/TR/wai-aria-practices-1.1/examples/menubar/menubar-1/menubar-1.html#) and navigate to the Admissions > Tuition submenu and hit escape, focus should be applied to "Tuition" but instead is applied to "Admissions"

**Comment by jongund** [comment] 2018-06-25 20:32
Fix is in pull request 740

**Comment by mcking65** [comment] 2018-06-27 05:46
This is fixed with commit 15b87d9. Thank you @jongund!

**Closed by mcking65** 2018-06-27 05:46 UTC
Labels: Feedback, bug, code example, question
