### ISSUE TITLE
Draft Combo Box design pattern

### ISSUE THREAD

**Issue by MichielBijl** [w3c/aria-practices#56] opened 2016-06-02 20:36 UTC
> A combo box enables the user to type in a field and at the same time chose a predefined value from a list.

[Combo Box in the APG](http://w3c.github.io/aria-practices/#combobox)

**Comment by mcking65** [comment] 2016-08-15 05:46
Duplicate of #31 so closing.

**Closed by mcking65** 2016-08-15 05:46 UTC
Labels: duplicate, needs review
