### ISSUE TITLE
Is there a plan for URL redirects for `1.2` examples that have been around for a while?

### ISSUE THREAD

**Issue by jnurthen** [w3c/aria-practices#2335] opened 2022-05-19 18:43 UTC
Is there a plan for URL redirects for `1.2` examples that have been around for a while? 
https://www.w3.org/TR/wai-aria-practices-1.2/examples/dialog-modal/dialog.html

How does one access the old `1.0` and `1.1` references? 
https://www.w3.org/TR/wai-aria-practices-1.1/examples/combobox/aria1.0pattern/combobox-autocomplete-both.html
https://www.w3.org/TR/wai-aria-practices-1.1/examples/combobox/aria1.1pattern/listbox-combo.html

_Originally posted by @joe-watkins in https://github.com/w3c/aria-practices/issues/2332#issuecomment-1131983413_

**Comment by jnurthen** [comment] 2022-05-19 18:44
Filed as a new issue as I think this deserves more visibility

**Comment by jnurthen** [comment] 2022-05-19 18:45
my personal opinion is that we should have redirects for examples which still exist but that old 1.0 and 1.1 examples should not be persisted as there are reasons they have been removed.

**Comment by KateMcTigueTR** [comment] 2022-05-19 19:32
I agree that URL redirects are necessary! We regularly link to Authoring Practices in our internal documentation. Finding and updating all those links is a huge undertaking, especially because the new URLs are so different from the old ones.

**Comment by ianktr** [comment] 2022-05-19 19:38
Agree with above comments - redirects please!

**Comment by slauriat** [comment] 2022-05-19 19:47
+1 (apologies if github provides a button for +1-ing an issue)

**Comment by luce-carevic** [comment] 2022-05-19 21:01
It would indeed really be helpful to have 301 redirects.

A colleague of mine had the unpleasant surprise to discover that the URL changed during her training session.

**Comment by SteveALee** [comment] 2022-05-20 08:50
cc @shawna-slh 

Hi I'm confused and could do with some clarification.  This seems to be asking for redirects and yes someone else is asking for no redirects?

But please note the WAI team generate the content of the w3.org/WAI pages but all hosting (including possible redirects) are manage by w3c. The WAI site content just appears within the w3.org domain.

The publication of the WAI APG pages will not have changed the TR note at all.

In fact TR notes are tightly controlled via the W3C process and all version remain available in perpetuity. Their URls and also URis out of them will never change between releases as that would break this requirement and cause chaos with broken bookmarked deep links (fragments).  

One advantage of the new WAI site web version of the APG content is it has a lighter publication process. In addition there is only ever the latest version.

Can you clarify which links where may need redirects and which may be broken?

This is really one for @michael-n-cooper though.

**Comment by yatil** [comment] 2022-05-20 11:14
Redirects are essential. Expired samples from 1.0 and 1.1 should redirect to a note that says “you followed an outdated link, we currently have no replacement for the content there”.

**Comment by SteveALee** [comment] 2022-05-20 11:32
So this is issue is about  the example URLs and not the TR itself?

But the TR seems to have been edited to remove all the content which seems like a complete No-no to me.  I must have not understood. TRs always have a link to latest version so do not need to be edited when latest changes - If people read the header.
A big clear text box could be added to the top, perhaps sticky for people following deep links.

Redirects are OK if someone wants to link to the latest but not if they want a specific version. Is it clear everyone wants the former? From a  previous comment it seems not! Or that might be because the TR not was altered? 

Also as the new WAI version is only ever the latest version no redirects are ever needed. I'm still unclear what the exact issue is. Are we only talking about redirects form some old examples to the new version? Redirects again seem dangerous to me.

Anyway - I leave it to others to resolve.

**Comment by AlainVagner** [comment] 2022-05-20 11:35
Hi. At the WAD monitoring body I am working for, we have produced [lots of reports](https://data.public.lu/fr/datasets/audits-simplifies-de-laccessibilite-numerique-2020-2021/) with direct links to patterns in the APG. Most of these links are now most probably dead. It would be cool to have redirects for all the previous APG URLs.

**Comment by SteveALee** [comment] 2022-05-20 11:38
So it seems the issue is the note has been changed breaking links!?

Well, yes,i n general, a URL is a ref to a resource. If that resource changes unexpectedly then something, somewhere will break.

Redirects seem like sticky plaster over a bad move to me.

**Comment by aardrian** [comment] 2022-05-20 11:40
@SteveALee here is a public example of something that links to a specific URL that is now 404:
https://adrianroselli.com/2020/07/aria-grid-as-an-anti-pattern.html

That post links to the following URL:
- https://www.w3.org/TR/wai-aria-practices-1.1/examples/grid/LayoutGrids.html

> In fact TR notes are tightly controlled via the W3C process and all versions remain available in perpetuity at the same URI. in addition URis out of them will never change or be redirected between releases as that would break this requirement and cause chaos with broken bookmarked deep links (fragments).

Note that the destination of that link lives in the `/TR/` path.

My suggestion is a 301 to the new pattern. If there is no new pattern, then something at that URL that acknowledges the page is gone with some minimal detail (it moved, was subsumed, was dropped, etc).

**Comment by yatil** [comment] 2022-05-20 11:44
Basically, the strategy should be:

1. Redirect everything under `https://www.w3.org/TR/wai-aria-practices-1.2/examples/*` so that it points to new patterns.
2. Put a message of obsoletion or update on `https://www.w3.org/TR/wai-aria-practices-1.2/` and redirect unused examples to it.

**Comment by SteveALee** [comment] 2022-05-20 11:51
hmm.

"unused examples"?

**Comment by yatil** [comment] 2022-05-20 11:52
The ones that are not used in the new iteration of the APG.

**Comment by SteveALee** [comment] 2022-05-20 11:53
@aardrian thank you. I finally understand the issue. I never expect that could happen to anything in TR space! I learn all the time.

**Comment by yatil** [comment] 2022-05-20 11:55
@SteveALee Working Group Notes (not Rec-Track documents!) can change at any time. And it looks like supporting material like the examples can be deleted, too. Not everything in `/TR/` space is on the rec track as a specification.

**Comment by SteveALee** [comment] 2022-05-20 11:58
Yes, thanks - I forgot was a note. Even though I typed that :) My bad

Another issue is that https://www.w3.org/TR/2021/NOTE-wai-aria-practices-1.2-20211129/ is also version 1.2 so there are now  two URI that point to differing versions of 1.2

I'm not surprised this has become confusing.

**Comment by SteveALee** [comment] 2022-05-20 12:00
Apologies for taking up so much bandwidth with my mis understanding.

**Comment by luce-carevic** [comment] 2022-05-20 12:08
> Basically, the strategy should be:
> 
>     1. Redirect everything under `https://www.w3.org/TR/wai-aria-practices-1.2/examples/*` so that it points to new patterns.

Beware the rule has a few exceptions:
- dialog_modal is now dialogmodal
- Listbox is now listbox
- TreeView is now treeview

**Comment by luce-carevic** [comment] 2022-05-20 12:36
@yatil : Yeah I understood it that way :) 

I made the mistake of just changing the URL (https://www.w3.org/TR/wai-aria-practices-1.2/examples/) in a small Alfred workflow I use not thinking that the name of the pattern in the URL could have changed. 

So I thought it was best to warn that it was not possible to just make a simple rule/change here.

**Comment by aardrian** [comment] 2022-05-23 12:05
A 404 reported against WCAG because of the APG URL changes:
https://github.com/w3c/wcag/issues/2457

Folks are spending time filing and resolving issues related to these 404s. It seems like a better use of _their_ time is for the APG links to get appropriate landing pages or redirects ASAP.

**Comment by thibaudcolas** [comment] 2022-05-24 10:01
Feels like the right thread to report this – right now if I Google "aria authoring practices", the first result is the `https://www.w3.org/TR/wai-aria-practices-1.1/`, the _W3C Group Note_.

<details>

<summary>Screenshot of the search results for reference</summary>

<img width="758" alt="Screenshot of Google search results for  aria authoring practices , wit the group note as the first result" src="https://user-images.githubusercontent.com/877585/170004494-7089b51d-76c3-4dd9-a665-6b43114a5d67.png">

</details>

That page’s title is `WAI-ARIA Authoring Practices 1.1 - W3C`, which is pretty confusing. Within the page, the link to the [APG](https://www.w3.org/WAI/aria/apg/) doesn’t stand out at all.

---

There needs to be consideration for `canonical` links, page-level banners to the new resources, and other common strategies to make the new resource discoverable and potentially transfer some of the SERP ranking of the old material to the new guides, like any site migration. Apologies if this is stating the obvious.

**Comment by besenwagen** [comment] 2022-05-24 11:34
For anybody who finds that useful, I created an ES module that exports an object with the old URLs mapped to the new ones.

https://github.com/besenwagen/apg-url-map

You have to figure out yourself how to actually replace URLs in your own resources though. ;-)

**Comment by yatil** [comment] 2022-05-24 11:57
@michael-n-cooper You should be able to [put the URLs containing /examples/ directly in the W3C redirection UI](https://github.com/besenwagen/apg-url-map/blob/main/docs/url-map.js). Everything with hashes needs an HTML document and a rewrite on client side.

**Comment by yatil** [comment] 2022-06-17 15:46
How is this issue still open after a month?

**Comment by mcking65** [comment] 2022-06-28 06:02
With support from the W3C web masters, we now have redirects in place for the following forms of APG URLs.

Version 1.1 aliases of form:
* https://www.w3.org/TR/wai-aria-practices-1.1/
* https://www.w3.org/TR/wai-aria-practices-1.1/examples/accordion/accordion.html

Version 1.2 aliases of form:
* https://www.w3.org/TR/wai-aria-practices-1.2/
* https://www.w3.org/TR/wai-aria-practices-1.2/examples/accordion/accordion.html

Unversioned aliases of form:
* https://www.w3.org/TR/wai-aria-practices/
* https://www.w3.org/TR/wai-aria-practices/examples/accordion/accordion.html

URLs that include a date are required by W3C TR policy to load the referenced resource. However, they now include a warning dialog. The warning tells the reader the resource is out of date and includes a URL that is redirected to the new site. For example:
* https://www.w3.org/TR/2021/NOTE-wai-aria-practices-1.2-20211129/
* https://www.w3.org/TR/2021/NOTE-wai-aria-practices-1.2-20211129/examples/accordion/accordion.html

The historical record of publications to the W3C Technical Resources site is available at:
https://www.w3.org/standards/history/wai-aria-practices-1.2

Both myself and other members of the team have spot tested the redirects and warnings. They all appear to be working. So, I am happy to be able to close this issue with many apologies to everyone who has been inconvenienced by this oversight in our initial launch plan.

**Closed by mcking65** 2022-06-28 06:02 UTC
Labels: enhancement, Feedback, Infrastructure

**Comment by mcking65** [comment] 2022-06-28 06:16
Note: the [editor's draft on github pages](http://w3c.github.io/aria-practices/) remains active and does not yet redirect people to the new site. We are still working on the plan to retire that version. For now, both the new site and the editor's draft are built from main, so the content is synchronized. They will remain synchronized until we build a version of the gh-pages branch that points people to the new site.
